export {
  Q1, Q2, Q4,
  P1, P2, P3, P5,
  L1_COST, L1_CONCRETE_BASE, L1_CONCRETE_OPTIONS,
  L2_TRIED_BASE, L2_TRIED_OPTIONS, L2_RESULT, L2_WHY,
  L3_IMPACT, L3_FEELING, L3_FUTURE,
  G1, G2,
} from './universal';
